### ISSUE TITLE
Roadside decor incomplete

### ISSUE THREAD

**Issue by kennatom** [Notuom/pikmin-bloom-checklist#2]
Thank you for expanding this Roadside Pikmin checklist to sticker letters! However, Pikmin Roadside stickers can be represented by numbers, as well as various colors of stickers as well (green, blue, yellow-orange I believe?) Not sure if there is interest in expanding the checklist to these variants.  Thank you!

**Comment by Notuom** [comment]
Thanks for your interest in this project!

For the number stickers, I wasn't aware those existed. It should be easy enough to add those.

I realized after implementing the list that there's actually color variations in the stickers. The problem with trying to keep track of that is that it then becomes a lot for people who don't need that much granularity.

I think this should be done as an "advanced" mode which can be toggled on the page so everyone can have the granularity they need.

**Comment by Notuom** [comment]
@kennatom I added the 0-9 stickers and the requested feature of separate colors albeit in a new view as described above. You'll now find a selection at the top where you can choose "Exhaustive" which separates roadside colors.

![image](https://user-images.githubusercontent.com/7154224/154899838-76286aeb-f08d-4124-8041-623018812417.png)

**Comment by kennatom** [comment]
Just saw the changes. Perfect solution. Doesn't overwhelm the new user. Provides continued goals to the veteran who may otherwise be giving up on the app. Thank you for the quick turn-around and a better solution than I could have thought of!
