### ISSUE TITLE
Chess Peices Black and White missing (all Color s)

### ISSUE THREAD

**Issue by parker2640** [Notuom/pikmin-bloom-checklist#38]

**Comment by parker2640** [comment]
There should two, one for Black and one White

**Comment by Notuom** [comment]
Ah thanks I was going through all the requests and missed that detail. Is the one that was there initially the black one? I can just add a new entry for white.

**Comment by parker2640** [comment]
Yes so it is just the white one missing

**Comment by parker2640** [comment]
But the icon I black 😅
