### ISSUE TITLE
Present Sticker (Gold) Decor

### ISSUE THREAD

**Issue by adastra168** [Notuom/pikmin-bloom-checklist#45]
4 special Present Sticker (Gold) 
only for red, yellow, blue, white

red, yellow, blue were available at Nintendo Live Seattle 2023 
I think there are other older events offer those decor

**Comment by Notuom** [comment]
Added based on https://www.reddit.com/r/PikminBloomApp/comments/167n6l2/so_i_was_able_to_grab_the_three_seattle_nintendo/, please file an issue to correct if the addition is inaccurate
