### ISSUE TITLE
Missing shiny restaurant Pikmin

### ISSUE THREAD

**Issue by StrangePan** [Notuom/pikmin-bloom-checklist#7]
Shiny restaurant Pikmin have been reported on the [subreddit](https://www.reddit.com/r/PikminBloomApp/). They are rare alternative decors found at restaurant locations, but are not listed in the in-game decor collection.

**Comment by Notuom** [comment]
Thanks, seems like only for red, yellow and blue Restaurant types according to https://www.pikminwiki.com/Decor_Pikmin#Rare_variants. I will add this under the Advanced view.
